const Hotels=[
    {id:1,
    name:'Recomended',
    innerimages:[require('../images/bed2.jpg'),require('../images/sitting1.jpg'),
    require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
    hotel:[{
        _id:'1',
        name:'Jordan Hotel',
        _price:' 453.54',
        _location:'Kimberley str 88 (Free State)',
        rating:'4.5',
        _image:require('../images/hotel6.jpg'),
        Aminities:['fastfood','pool',
            'wifi','tv'],
        innerimages:[require('../images/bed2.jpg'),require('../images/sitting1.jpg'),
        require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
        coordinates:{  latitude:-23.896172,
            longitude:29.448626,
            latitudeDelta:0.015,
            longitudeDelta:0.0121,},
            Room1:{name:'Standard Room',price:900.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:700.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
           
    },
    {
        _id:'2',
        name:'Roadstar Hotel',
        _price:' 746.83',
        _location:'Phalaborwa str 42 (Limpopo) ',
        rating:'4.5',
        _image:require('../images/hotel3.jpg'),
        Aminities:['fastfood','pool',
            'wifi','tv'],
        innerimages:[require('../images/bed3.jpg'),require('../images/sitting2.jpg'),
        require('../images/bathroom2.jpg'),require('../images/balcony1.jpg')],
        coordinates:{latitude: 48.8587741,
            longitude: 2.2069771,
            latitudeDelta:0.015,
            longitudeDelta:0.0121,},
            Room1:{name:'Standard Room',price:900.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:700.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:750.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'3',
        name:'Jordan Hotel',
        _price:'548.84',
        _location:'Johannesburg str 16 (Gauteng)',
        rating:'4.5',
       _image:require('../images/hotel4.jpg'),
       Aminities:['fastfood','pool',
            'wifi','tv'],
       innerimages:[require('../images/bed4.jpg'),require('../images/sitting4.jpg'),
        require('../images/bathroom3.jpg'),require('../images/balcony9.jpg')],
        coordinates:{latitude: 48.8587741,
            longitude: 2.2069771,
            latitudeDelta:0.015,
            longitudeDelta:0.0121,},
            Room1:{name:'Standard Room',price:900.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:700.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:850.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'4',
        name:'Indigo Hotel',
        _price:'846.95',
        _location:'Soweto str 78 (Gauteng)',
        rating:'3.5',
       _image:require('../images/hotel2.jpg'),
       Aminities:['fastfood','pool',
            'wifi','tv'],
       innerimages:[require('../images/bed5.jpg'),require('../images/sitting5.jpg'),
       require('../images/bathroom4.jpg'),require('../images/balcony8.jpg')],
       coordinates:{latitude: 48.8587741,
        longitude: 2.2069771,
        latitudeDelta:0.015,
        longitudeDelta:0.0121,},
        Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:850.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },]},
    {id:1,
        name:'Popular',
        hotel:[{
            _id:'1',
            name:'Jordan Hotel',
            _price:' 453.54',
            _location:'Polokwane',
            rating:'2.5',
            _image:require('../images/hotel1.jpg'),
            Aminities:['fastfood','pool',
                'wifi','tv'],
            innerimages:[require('../images/bed6.jpg'),require('../images/sitting1.jpg'),
            require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
            coordinates:{latitude: 48.8587741,
                longitude: 2.2069771,
                latitudeDelta:0.015,
                longitudeDelta:0.0121,},
                Room1:{name:'Standard Room',price:550.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:860.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
        },
        {
            _id:'2',
            name:'Indigo Hotel',
            _price:' 746.83',
            _location:'Bloemfontein str 35 (Free State)',
            rating:'3.5',
            _image:require('../images/hotel5.jpg'),
            Aminities:['fastfood','pool',
                'wifi','tv'],
            innerimages:[require('../images/bed7.jpg'),require('../images/sitting2.jpg'),
            require('../images/bathroom10.jpg'),require('../images/balcony1.jpg')],
            coordinates:{latitude: 48.8587741,
                longitude: 2.2069771,
                latitudeDelta:0.015,
                longitudeDelta:0.0121,},
                Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:800.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
        },
        {
            _id:'3',
            name:'Roadstar Hotel',
            _price:'548.84',
            _location:'Pretoria str 84 (Gauteng)',
            rating:'2.5',
           _image:require('../images/hotel18.jpg'),
           Aminities:['fastfood','pool',
                'wifi','tv'],
           innerimages:[require('../images/bed8.jpg'),require('../images/sitting4.jpg'),
            require('../images/bathroom3.jpg'),require('../images/balcony9.jpg')],
            coordinates:{latitude: 48.8587741,
                longitude: 2.2069771,
                latitudeDelta:0.015,
                longitudeDelta:0.0121,},
                Room1:{name:'Standard Room',price:700.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:840.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Romm',price:1200.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
        },
        {
            _id:'4',
            name:'Indigo Hotel',
            _price:'846.95',
            _location:'Stellenbosch str 25 (Western Cape)',
            rating:'3.5',
           _image:require('../images/hotel24.jpg'),
           Aminities:['fastfood','pool',
                'wifi','tv'],
           innerimages:[require('../images/bed9.jpg'),require('../images/sitting4.jpg'),
           require('../images/bathroom9.jpg'),require('../images/balcony8.jpg')]
           ,coordinates:{latitude: 48.8587741,
            longitude: 2.2069771,
            latitudeDelta:0.015,
            longitudeDelta:0.0121,},
            Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:890.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
        },]},
        {id:1,
            name:'Top Ratings',
            hotel:[{
                _id:'1',
                name:'Roadstar Hotel',
                _price:' 453.54',
                _location:'Pietermaritzburg str 86(KwaZulu-Natal)',
                rating:'4.5',
                _image:require('../images/hotel19.jpg'),
                Aminities:['fastfood','pool',
                    'wifi','tv'],
                innerimages:[require('../images/bed2.jpg'),require('../images/sitting1.jpg'),
                require('../images/bathroom7.jpg'),require('../images/balcony4.jpg')],
                coordinates:{latitude: 48.8587741,
                    longitude: 2.2069771,
                    latitudeDelta:0.015,
                    longitudeDelta:0.0121,},
                    Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:860.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
            },
            {
                _id:'2',
                name:'Indigo Hotel',
                _price:' 746.83',
                _location:'Durban str 79 (kwaZulu-Natal)',
                rating:'4.7',
                _image:require('../images/hotel10.jpg'),
                Aminities:['fastfood','pool',
                    'wifi','tv'],
                innerimages:[require('../images/bed10.jpg'),require('../images/sitting2.jpg'),
                require('../images/bathroom6.jpg'),require('../images/balcony3.jpg')],
                coordinates:{latitude: 48.8587741,
                    longitude: 2.2069771,
                    latitudeDelta:0.015,
                    longitudeDelta:0.0121,},
                    Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:960.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
            },
            {
                _id:'3',
                name:'Jordan Hotel',
                _price:'548.84',
                _location:'cape town str 13 (Westen Cape)',
                rating:'4.9',
               _image:require('../images/hotel11.jpg'),
               Aminities:['fastfood','pool',
                    'wifi','tv'],
               innerimages:[require('../images/bed4.jpg'),require('../images/sitting4.jpg'),
                require('../images/bathroom8.jpg'),require('../images/balcony2.jpg')],
                coordinates:{latitude: 48.8587741,
                    longitude: 2.2069771,
                    latitudeDelta:0.015,
                    longitudeDelta:0.0121,},
                    Room1:{name:'Standard Room',price:500.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:600.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:750.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:890.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
            },
            {
                _id:'4',
                name:'Jordan Hotel',
                _price:'846.95',
                _location:'Santon str 12(Gauteng)',
                rating:'4.6',
               _image:require('../images/hotel12.jpg'),
               Aminities:['fastfood','pool',
                    'wifi','tv'],
               innerimages:[require('../images/bed5.jpg'),require('../images/sitting4.jpg'),
               require('../images/bathroom9.jpg'),require('../images/balcony1.jpg')],
               coordinates:{latitude: 48.8587741,
                longitude: 2.2069771,
                latitudeDelta:0.015,
                longitudeDelta:0.0121,},
                Room1:{name:'Standard Room',price:500.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:600.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:7500.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:890.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
            },]},
            {id:4,
                name:'Near Your',
                hotel:[{
                    _id:'1',
                    name:'Indigo Hotel',
                    _price:' 453.54',
                    _location:'Thohayandou str 45 Venda (Limpopo)',
                    rating:'3.8',
                    _image:require('../images/hotel23.jpg'),
                    Aminities:['fastfood','pool',
                        'wifi','tv'],
                    innerimages:[require('../images/bed2.jpg'),require('../images/sitting1.jpg'),
                    require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
                    coordinates:{latitude: 48.8587741,
                        longitude: 2.2069771,
                        latitudeDelta:0.015,
                        longitudeDelta:0.0121,},
                        Room1:{name:'Standard Room',price:500.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:600.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:7500.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:890.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
                },
                {
                    _id:'2',
                    name:'Roadstar Hotel',
                    _price:' 746.83',
                    _location:'Polokwane Bicard 45(Limpopo)',
                    rating:'3.8',
                    _image:require('../images/hotel22.jpg'),
                    Aminities:['fastfood','pool',
                        'wifi','tv'],
                    innerimages:[require('../images/bed3.jpg'),require('../images/sitting2.jpg'),
                    require('../images/bathroom10.jpg'),require('../images/balcony8.jpg')],
                    coordinates:{latitude: 48.8587741,
                        longitude: 2.2069771,
                        latitudeDelta:0.015,
                        longitudeDelta:0.0121,},
                        Room1:{name:'Standard Room',price:500.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:600.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:750.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:890.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
                },
                {
                    _id:'3',
                    _price:'548.84',
                    name:'Indigo Hotel',
                    _location:'Savanna str 25 polokwane(Limpopo)',
                    rating:'2.7',
                   _image:require('../images/hotel21.jpg'),
                   Aminities:['fastfood','pool',
                        'wifi','tv'],
                   innerimages:[require('../images/bed4.jpg'),require('../images/sitting4.jpg'),
                    require('../images/bathroom3.jpg'),require('../images/balcony9.jpg')],
                    coordinates:{latitude: 48.8587741,
                        longitude: 2.2069771,
                        latitudeDelta:0.015,
                        longitudeDelta:0.0121,},
                        Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:650.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:750.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:950.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
                },
                {
                    _id:'4',
                    name:'Roadstar Hotel',
                    _price:'846.95',
                    _location:'Thornhill str 77 polokwane (Limpopo)',
                    rating:'4.5',
                   _image:require('../images/hotel20.jpg'),
                   Aminities:['fastfood','pool',
                        'wifi','tv'],
                   innerimages:[require('../images/bed5.jpg'),require('../images/sitting4.jpg'),
                   require('../images/bathroom4.jpg'),require('../images/balcony6.jpg')],
                   coordinates:{latitude: 48.8587741,
                    longitude: 2.2069771,
                    latitudeDelta:0.015,
                    longitudeDelta:0.0121,},
                    Room1:{name:'Standard Room',price:7500.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:800.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:9500.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
                },]}
]
export default Hotels