const NearHotels=[
    {
        _id:'1',
        hotelname:'Jordan',
        _price:' 453.54',
        _location:'Polokwane',
        rating:'4.5',
        _image:require('../images/hotel6.jpg'),
        Aminities:['fastfood','pool',
            'wifi','tv'],
        innerimages:[require('../images/bed2.jpg'),require('../images/sitting1.jpg'),
        require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
        coordinates:{  latitude:-23.896172,
            longitude:29.448626,
            latitudeDelta:0.015,
            longitudeDelta:0.0121,},
            Room1:{name:'Standard Room',price:900.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
            Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
            Room3:{name:'Executive Room',price:700.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
            Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'2',
        hotelname:'Leah',
        _price:'846.95',
        _location:'Thornhill',
        rating:'3.5',
       _image:require('../images/hotel2.jpg'),
       Aminities:['fastfood','pool',
            'wifi','tv'],
       innerimages:[require('../images/bed5.jpg'),require('../images/sitting5.jpg'),
       require('../images/bathroom4.jpg'),require('../images/balcony8.jpg')],
       coordinates:{latitude: 48.8587741,
        longitude: 2.2069771},
        Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:850.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'3',
        hotelname:'Jordan',
        _price:' 453.54',
        _location:'Polokwane',
        rating:'2.5',
        _image:require('../images/hotel1.jpg'),
        Aminities:['fastfood','pool',
            'wifi','tv'],
        innerimages:[require('../images/bed6.jpg'),require('../images/sitting1.jpg'),
        require('../images/bathroom1.jpg'),require('../images/balcony4.jpg')],
        coordinates:{latitude: 48.8587741,
            longitude: 2.2069771},
            Room1:{name:'Standard Room',price:550.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:860.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'4',
        hotelname:'Jordan',
        _price:' 746.83',
        _location:'Durban',
        rating:'3.5',
        _image:require('../images/hotel5.jpg'),
        Aminities:['fastfood','pool',
            'wifi','tv'],
        innerimages:[require('../images/bed7.jpg'),require('../images/sitting2.jpg'),
        require('../images/bathroom10.jpg'),require('../images/balcony1.jpg')],
        coordinates:{latitude: 48.8587741,
            longitude: 2.2069771},
            Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:800.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Romm',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'5',
        hotelname:'Jordan',
        _price:'548.84',
        _location:'cape town',
        rating:'2.5',
       _image:require('../images/hotel18.jpg'),
       Aminities:['fastfood','pool',
            'wifi','tv'],
       innerimages:[require('../images/bed8.jpg'),require('../images/sitting4.jpg'),
        require('../images/bathroom3.jpg'),require('../images/balcony9.jpg')],
        coordinates:{latitude: 48.8587741,
            longitude: 2.2069771},
            Room1:{name:'Standard Room',price:700.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:840.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Romm',price:1200.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'},
    },
    {
        _id:'6',
        hotelname:'Jordan',
        _price:'846.95',
        _location:'Thornhill',
        rating:'3.5',
       _image:require('../images/hotel24.jpg'),
       Aminities:['fastfood','pool',
            'wifi','tv'],
       innerimages:[require('../images/bed9.jpg'),require('../images/sitting4.jpg'),
       require('../images/bathroom9.jpg'),require('../images/balcony8.jpg')]
       ,coordinates:{latitude: 48.8587741,
        longitude: 2.2069771},
        Room1:{name:'Standard Room',price:600.00,bedtype:'2 king beds',image:require('../images/twinbed2.jpg'),rating:'4.5'},
        Room2:{name:'Standard Room',price:750.00,bedtype:'1 Queen bed',image:require('../images/bed2.jpg'),rating:'4.5'},
        Room3:{name:'Executive Room',price:890.00,bedtype:'1 king bed',image:require('../images/bed3.jpg'),rating:'4.5'},
        Room4:{name:'Executive Room',price:1060.00,bedtype:'2 Queen beds',image:require('../images/twinbed3.jpg'),rating:'4.5'}, _id:'4',
        _price:'846.95',
        _location:'Thornhill',
        hotelname:'Calyn',
        rating:'3.8',
       _image:require('../images/hotel2.jpg')
    },
]
export default NearHotels